/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_yonghao_test_android_serialport_api_SerialPort */

#ifndef _Included_com_shbst_bst_tftdisplay_15_h_SerialPort_SerialPort
#define _Included_com_shbst_bst_tftdisplay_15_h_SerialPort_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_yonghao_test_android_serialport_api_SerialPort
 * Method:    open   com_bst_demo_bst_villaproject_SerialPort
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_shbst_bst_tftdisplay_115_1h_SerialPort_SerialPort_open(JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_example_yonghao_test_android_serialport_api_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_shbst_bst_tftdisplay_115_1h_SerialPort_SerialPort_close(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
